- name: Only allow vm_center_managed
  fail:
    msg: "vm_vcenter_managed must be true and vCenter must be up and running."
  when: vm_vcenter_managed is undefined or vm_vcenter_managed == False

- name: Create virtual machine (vcenter)
  delegate_to: localhost
  when:
    - vm_vcenter_managed is defined
    - vm_vcenter_managed == True
  vmware_guest:
    hostname: "{{ vcenter_hostname | mandatory }}"
    username: "{{ vcenter_username | mandatory }}"
    password: "{{ vcenter_password | mandatory }}"
    datacenter: "{{ vcenter_datacenter | mandatory }}"
    validate_certs: "{{ vcenter_validate_certs | default(no) }}"
    template: "{{ vm_template | default(omit) }}"
    folder: "{{ vm_vcenter_path | default( vcenter_datacenter + '/' + (vm_folder | default('')) + '/vm' ) }}"
    name: "{{ vm_name | mandatory }}"
    state: "{{ vm_state | default('poweredon') }}"
    esxi_hostname: "{{ esxi_hostname | mandatory }}"
    networks:
    - name: "{{ vm_network | default('VM Network') }}"
      device_type: "{{ vm_network_device | default('vmxnet3') }}"
  register: deploy_vm
